### ISSUE TITLE
keyerror  radar

### ISSUE THREAD

**Issue by YueWangTO** [Tsinghua-MARS-Lab/futr3d#42]
when running camera＋radar training，the error occured

2023-07-28 12:31:40.542790: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "tools/train.py", line 318, in <module>
    main()
  File "tools/train.py", line 314, in main
    meta=meta)
  File "/home/mmdetection3d-1.0.0rc4/mmdet3d/apis/train.py", line 351, in train_model
    meta=meta)
  File "/home/mmdetection3d-1.0.0rc4/mmdet3d/apis/train.py", line 319, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/root/anaconda3/envs/futr3d-1/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/root/anaconda3/envs/futr3d-1/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 49, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/root/anaconda3/envs/futr3d-1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/futr3d-1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/root/anaconda3/envs/futr3d-1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/root/anaconda3/envs/futr3d-1/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/futr3d-1/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/envs/futr3d-1/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/futr3d-1/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mmdetection3d-1.0.0rc4/mmdet3d/datasets/custom_3d.py", line 435, in __getitem__
    data = self.prepare_train_data(idx)
  File "/home/mmdetection3d-1.0.0rc4/mmdet3d/datasets/custom_3d.py", line 229, in prepare_train_data
    example = self.pipeline(input_dict)
  File "/home/mmdetection3d-1.0.0rc4/mmdet3d/datasets/pipelines/compose.py", line 49, in __call__
    data = t(data)
  File "/tmp/algorithm/plugin/futr3d/datasets/loading.py", line 417, in __call__
    radars_dict = results['radar']
KeyError: 'radar'

it seems that mmdet3d can not load radar info, could you please tell me how to solve this problem?

**Comment by YueWangTO** [comment]
mmdet3d must be installed using the mmdet3d package in this project, otherwise, mmdet3d cam not be able to read radar data
