### ISSUE TITLE
Evaluation of pre-trained model

### ISSUE THREAD

**Issue by KevinCodeGitHub** [Tsinghua-MARS-Lab/futr3d#57]
I want to try to run an evaluation of a pretrained model on nuscenes data to recreate results and confirm that my installation has been compleated succesfully. I am currently trying to run : 
bash tools/dist_test.sh plugin/configs/lidar_cam/lidar_0075v_cam_vov.py checkpoints/lidar_0075_cam_vov.pth --eval bbox

**I get the following error:**

File "/mmdetection3d/mmdet3d/datasets/nuscenes_dataset.py", line 188, in load_annotations
    data_infos = list(sorted(data['infos'], key=lambda e: e['timestamp']))
KeyError: 'infos'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test.py", line 284, in <module>
    main()
  File "tools/test.py", line 227, in main
    dataset = build_dataset(cfg.data.test)
  File "/mmdetection3d/mmdet3d/datasets/builder.py", line 44, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "NuScenesDataset: 'infos'"

**I would appreciate any recommendations!**

**Comment by KevinCodeGitHub** [comment]
I realized that the error message indicates that the script encountered a KeyError while attempting to load annotations from the NuScenes dataset. Specifically, it failed to find the expected key 'infos' in the dataset dictionary.
Upon further investigation, it appears that my .pkl files containing the dataset annotations had incorrect key labels. The script expected the key to be 'infos', but it was actually labeled as 'data_list'. This discrepancy caused the script to be unable to recognize and process the dataset information correctly.
